spring.application.name=fintech-transfer

spring.datasource.url=jdbc:postgresql://postgres:5432/database
spring.datasource.username=Paul
spring.datasource.password=Ukhov
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database=POSTGRESQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080